// FILE: src/components/admin/blog-editor-v2/block-tools.tsx
/**
 * Definición de todas las herramientas/bloques disponibles
 */

import {
  Type,
  Image as ImageIcon,
  CreditCard,
  LayoutGrid,
  ChevronDown,
  AlertCircle,
  Minus,
  FileCode,
  Video,
  Twitter,
  Table,
  Lightbulb,
  MousePointerClick,
  Quote,
  TrendingUp,
  Clock,
  GitCompare,
  Download,
  Code2,
} from 'lucide-react';
import { BlockToolDefinition } from './types';

export const BLOCK_TOOLS: BlockToolDefinition[] = [
  {
    id: 'text',
    type: 'text',
    label: 'Texto',
    icon: Type,
    description: 'Párrafos, títulos, listas',
    category: 'content',
  },
  {
    id: 'image',
    type: 'image',
    label: 'Imagen',
    icon: ImageIcon,
    description: 'Sube o enlaza imágenes',
    category: 'media',
  },
  {
    id: 'program-card',
    type: 'program-card',
    label: 'Programa',
    icon: CreditCard,
    description: 'Tarjeta de programa',
    category: 'content',
  },
  {
    id: 'programs-grid',
    type: 'programs-grid',
    label: 'Grid Programas',
    icon: LayoutGrid,
    description: 'Múltiples programas en columnas',
    category: 'content',
  },
  {
    id: 'images-grid',
    type: 'images-grid',
    label: 'Grid Imágenes',
    icon: ImageIcon,
    description: 'Múltiples imágenes en columnas',
    category: 'media',
  },
  {
    id: 'tabs',
    type: 'tabs',
    label: 'Pestañas',
    icon: LayoutGrid,
    description: 'Contenido en tabs',
    category: 'interactive',
  },
  {
    id: 'accordion',
    type: 'accordion',
    label: 'Acordeón',
    icon: ChevronDown,
    description: 'Contenido expandible',
    category: 'interactive',
  },
  {
    id: 'alert',
    type: 'alert',
    label: 'Alerta',
    icon: AlertCircle,
    description: 'Mensajes destacados',
    category: 'content',
  },
  {
    id: 'code',
    type: 'code',
    label: 'Código',
    icon: FileCode,
    description: 'Bloques de código',
    category: 'content',
  },
  {
    id: 'separator',
    type: 'separator',
    label: 'Separador',
    icon: Minus,
    description: 'Línea divisoria',
    category: 'layout',
  },
  {
    id: 'video',
    type: 'video',
    label: 'Video',
    icon: Video,
    description: 'YouTube, Vimeo, Loom',
    category: 'media',
  },
  {
    id: 'tweet',
    type: 'tweet',
    label: 'Tweet',
    icon: Twitter,
    description: 'Embed de Twitter',
    category: 'media',
  },
  {
    id: 'table',
    type: 'table',
    label: 'Tabla',
    icon: Table,
    description: 'Tabla editable',
    category: 'content',
  },
  {
    id: 'callout',
    type: 'callout',
    label: 'Callout',
    icon: Lightbulb,
    description: 'Nota destacada',
    category: 'content',
  },
  {
    id: 'button',
    type: 'button',
    label: 'Botón',
    icon: MousePointerClick,
    description: 'Call to action',
    category: 'interactive',
  },
  {
    id: 'divider-text',
    type: 'divider-text',
    label: 'Divider con Texto',
    icon: Minus,
    description: 'Separador con etiqueta',
    category: 'layout',
  },
  {
    id: 'quote',
    type: 'quote',
    label: 'Cita',
    icon: Quote,
    description: 'Cita con autor',
    category: 'content',
  },
  {
    id: 'stats',
    type: 'stats',
    label: 'Estadísticas',
    icon: TrendingUp,
    description: 'Grid de métricas',
    category: 'content',
  },
  {
    id: 'timeline',
    type: 'timeline',
    label: 'Timeline',
    icon: Clock,
    description: 'Línea de tiempo',
    category: 'content',
  },
  {
    id: 'comparison',
    type: 'comparison',
    label: 'Comparación',
    icon: GitCompare,
    description: 'Tabla comparativa',
    category: 'content',
  },
  {
    id: 'file-download',
    type: 'file-download',
    label: 'Descarga',
    icon: Download,
    description: 'Archivo descargable',
    category: 'interactive',
  },
  {
    id: 'embed',
    type: 'embed',
    label: 'Embed',
    icon: Code2,
    description: 'Código HTML/iframe',
    category: 'media',
  },
];

export const BLOCK_CATEGORIES = {
  content: { label: 'Contenido', color: 'text-blue-500' },
  media: { label: 'Medios', color: 'text-purple-500' },
  interactive: { label: 'Interactivo', color: 'text-green-500' },
  layout: { label: 'Diseño', color: 'text-orange-500' },
} as const;
