// FILE: src/components/admin/blog-editor-v2/block-tools.tsx
/**
 * Definición de todas las herramientas/bloques disponibles
 */

import {
  Type,
  Image as ImageIcon,
  CreditCard,
  LayoutGrid,
  ChevronDown,
  AlertCircle,
  Minus,
  FileCode,
  Video,
  Twitter,
  Table,
  Lightbulb,
  MousePointerClick,
  Quote,
  TrendingUp,
  Clock,
  GitCompare,
  Download,
  Code2,
  HelpCircle,
  ThumbsUp,
  Grid3x3,
  ArrowLeftRight,
  Sparkles,
  Folder,
  User,
  BarChart3,
  CheckSquare,
  FileText,
  DollarSign,
  Star,
  AlertTriangle,
  Megaphone,
  Package,
  MessageSquare,
  List,
  Mail,
  Github,
  Network,
  Calculator,
  Music,
  Instagram,
  Bell,
} from 'lucide-react';
import { BlockToolDefinition } from './types';

export const BLOCK_TOOLS: BlockToolDefinition[] = [
  // === BÁSICOS ===
  {
    id: 'text',
    type: 'text',
    label: 'Texto',
    icon: Type,
    description: 'Párrafos, títulos, listas',
    category: 'basics',
  },
  {
    id: 'image',
    type: 'image',
    label: 'Imagen',
    icon: ImageIcon,
    description: 'Sube o enlaza imágenes',
    category: 'basics',
  },
  {
    id: 'quote',
    type: 'quote',
    label: 'Cita',
    icon: Quote,
    description: 'Cita con autor',
    category: 'basics',
  },
  {
    id: 'separator',
    type: 'separator',
    label: 'Separador',
    icon: Minus,
    description: 'Línea divisoria',
    category: 'basics',
  },
  {
    id: 'divider-text',
    type: 'divider-text',
    label: 'Divider con Texto',
    icon: Minus,
    description: 'Separador con etiqueta',
    category: 'basics',
  },

  // === CONTENIDO ===
  {
    id: 'toc',
    type: 'toc',
    label: 'Tabla de Contenidos',
    icon: List,
    description: 'Índice automático del post',
    category: 'content',
  },
  {
    id: 'alert',
    type: 'alert',
    label: 'Alerta',
    icon: AlertCircle,
    description: 'Mensajes destacados',
    category: 'content',
  },
  {
    id: 'callout',
    type: 'callout',
    label: 'Callout',
    icon: Lightbulb,
    description: 'Nota destacada',
    category: 'content',
  },
  {
    id: 'tip-box',
    type: 'tip-box',
    label: 'Caja de Tip',
    icon: AlertTriangle,
    description: 'Tips, warnings, info',
    category: 'content',
  },
  {
    id: 'notification',
    type: 'notification',
    label: 'Notificación',
    icon: Bell,
    description: 'Mensaje de notificación',
    category: 'content',
  },
  {
    id: 'table',
    type: 'table',
    label: 'Tabla',
    icon: Table,
    description: 'Tabla editable',
    category: 'content',
  },
  {
    id: 'stats',
    type: 'stats',
    label: 'Estadísticas',
    icon: TrendingUp,
    description: 'Grid de métricas',
    category: 'content',
  },
  {
    id: 'timeline',
    type: 'timeline',
    label: 'Timeline',
    icon: Clock,
    description: 'Línea de tiempo',
    category: 'content',
  },
  {
    id: 'comparison',
    type: 'comparison',
    label: 'Comparación',
    icon: GitCompare,
    description: 'Tabla comparativa',
    category: 'content',
  },
  {
    id: 'faq',
    type: 'faq',
    label: 'FAQ',
    icon: HelpCircle,
    description: 'Preguntas frecuentes con SEO',
    category: 'content',
  },
  {
    id: 'pros-cons',
    type: 'pros-cons',
    label: 'Pros & Cons',
    icon: ThumbsUp,
    description: 'Ventajas y desventajas',
    category: 'content',
  },
  {
    id: 'feature-list',
    type: 'feature-list',
    label: 'Lista de Features',
    icon: Sparkles,
    description: 'Características con iconos',
    category: 'content',
  },
  {
    id: 'icon-grid',
    type: 'icon-grid',
    label: 'Grid de Iconos',
    icon: Grid3x3,
    description: 'Grid con iconos y texto',
    category: 'content',
  },
  {
    id: 'author-bio',
    type: 'author-bio',
    label: 'Bio de Autor',
    icon: User,
    description: 'Biografía del autor',
    category: 'content',
  },
  {
    id: 'category-card',
    type: 'category-card',
    label: 'Categoría',
    icon: Folder,
    description: 'Tarjeta de categoría',
    category: 'content',
  },

  // === MEDIOS ===
  {
    id: 'video',
    type: 'video',
    label: 'Video',
    icon: Video,
    description: 'YouTube, Vimeo, Loom',
    category: 'media',
  },
  {
    id: 'images-grid',
    type: 'images-grid',
    label: 'Grid Imágenes',
    icon: ImageIcon,
    description: 'Múltiples imágenes en columnas',
    category: 'media',
  },
  {
    id: 'before-after',
    type: 'before-after',
    label: 'Before/After',
    icon: ArrowLeftRight,
    description: 'Comparador de imágenes',
    category: 'media',
  },
  {
    id: 'tweet',
    type: 'tweet',
    label: 'Tweet',
    icon: Twitter,
    description: 'Embed de Twitter',
    category: 'media',
  },
  {
    id: 'instagram',
    type: 'instagram',
    label: 'Instagram Post',
    icon: Instagram,
    description: 'Post de Instagram simulado',
    category: 'media',
  },
  {
    id: 'reddit-post',
    type: 'reddit-post',
    label: 'Reddit Post',
    icon: MessageSquare,
    description: 'Post de Reddit simulado',
    category: 'media',
  },
  {
    id: 'spotify',
    type: 'spotify',
    label: 'Spotify',
    icon: Music,
    description: 'Embed de Spotify',
    category: 'media',
  },
  {
    id: 'embed',
    type: 'embed',
    label: 'Embed',
    icon: Code2,
    description: 'Código HTML/iframe',
    category: 'media',
  },

  // === PROGRAMAS Y BLOGS ===
  {
    id: 'program-card',
    type: 'program-card',
    label: 'Programa',
    icon: CreditCard,
    description: 'Tarjeta de programa',
    category: 'programs',
  },
  {
    id: 'programs-grid',
    type: 'programs-grid',
    label: 'Grid Programas',
    icon: LayoutGrid,
    description: 'Múltiples programas en columnas',
    category: 'programs',
  },
  {
    id: 'blog-card',
    type: 'blog-card',
    label: 'Blog',
    icon: CreditCard,
    description: 'Tarjeta de blog',
    category: 'programs',
  },
  {
    id: 'blogs-grid',
    type: 'blogs-grid',
    label: 'Grid Blogs',
    icon: LayoutGrid,
    description: 'Múltiples blogs en columnas',
    category: 'programs',
  },

  // === INTERACTIVOS ===
  {
    id: 'button',
    type: 'button',
    label: 'Botón',
    icon: MousePointerClick,
    description: 'Call to action',
    category: 'interactive',
  },
  {
    id: 'tabs',
    type: 'tabs',
    label: 'Pestañas',
    icon: LayoutGrid,
    description: 'Contenido en tabs',
    category: 'interactive',
  },
  {
    id: 'accordion',
    type: 'accordion',
    label: 'Acordeón',
    icon: ChevronDown,
    description: 'Contenido expandible',
    category: 'interactive',
  },
  {
    id: 'poll',
    type: 'poll',
    label: 'Encuesta',
    icon: BarChart3,
    description: 'Poll con resultados en vivo',
    category: 'interactive',
  },
  {
    id: 'progress-bar',
    type: 'progress-bar',
    label: 'Barra de Progreso',
    icon: TrendingUp,
    description: 'Barras de progreso animadas',
    category: 'interactive',
  },
  {
    id: 'checklist',
    type: 'checklist',
    label: 'Checklist',
    icon: CheckSquare,
    description: 'Lista de tareas interactiva',
    category: 'interactive',
  },
  {
    id: 'file-download',
    type: 'file-download',
    label: 'Descarga',
    icon: Download,
    description: 'Archivo descargable',
    category: 'interactive',
  },

  // === CONVERSIÓN ===
  {
    id: 'newsletter',
    type: 'newsletter',
    label: 'Newsletter',
    icon: Mail,
    description: 'Formulario de suscripción',
    category: 'conversion',
  },
  {
    id: 'cta-banner',
    type: 'cta-banner',
    label: 'Banner CTA',
    icon: Megaphone,
    description: 'Banner de llamada a acción',
    category: 'conversion',
  },
  {
    id: 'pricing-table',
    type: 'pricing-table',
    label: 'Tabla de Precios',
    icon: DollarSign,
    description: 'Comparación de planes',
    category: 'conversion',
  },
  {
    id: 'testimonial',
    type: 'testimonial',
    label: 'Testimonio',
    icon: Star,
    description: 'Testimonio destacado',
    category: 'conversion',
  },
  {
    id: 'product-showcase',
    type: 'product-showcase',
    label: 'Showcase Programa',
    icon: Package,
    description: 'Destacar programa con features',
    category: 'conversion',
  },

  // === CÓDIGO Y TÉCNICO ===
  {
    id: 'code',
    type: 'code',
    label: 'Código',
    icon: FileCode,
    description: 'Bloques de código',
    category: 'code',
  },
  {
    id: 'gist',
    type: 'gist',
    label: 'GitHub Gist',
    icon: Github,
    description: 'Embed de Gist',
    category: 'code',
  },
  {
    id: 'mermaid',
    type: 'mermaid',
    label: 'Diagrama Mermaid',
    icon: Network,
    description: 'Diagramas y flowcharts',
    category: 'code',
  },
  {
    id: 'math',
    type: 'math',
    label: 'Fórmula Matemática',
    icon: Calculator,
    description: 'Ecuaciones LaTeX',
    category: 'code',
  },
  {
    id: 'changelog',
    type: 'changelog',
    label: 'Changelog',
    icon: FileText,
    description: 'Historial de cambios',
    category: 'code',
  },
];

export const BLOCK_CATEGORIES = {
  favorites: { label: 'Favoritos', color: 'text-rose-500', icon: '❤️' },
  basics: { label: 'Básicos', color: 'text-slate-600', icon: '📝' },
  content: { label: 'Contenido', color: 'text-blue-500', icon: '📄' },
  media: { label: 'Medios', color: 'text-purple-500', icon: '🎬' },
  programs: { label: 'Programas & Blogs', color: 'text-cyan-500', icon: '🎓' },
  interactive: { label: 'Interactivo', color: 'text-green-500', icon: '⚡' },
  conversion: { label: 'Conversión', color: 'text-red-500', icon: '🎯' },
  code: { label: 'Código & Técnico', color: 'text-orange-500', icon: '💻' },
} as const;
